name: C++ Build with CMake

on:
  push:
    branches:
      - feature/workflows # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest # You can also use macos-latest for macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize and update submodule
      run: git submodule update --init --recursive

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.27'

    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install libsfml-dev

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ../
        make
