name: Perft Pos3

on:
  push:
    branches:
      - main # Change this to your main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: perft3
    runs-on: ubuntu-latest # You can also use macos-latest for macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.27'

    - name: Install SFML
      run: |
        sudo apt-get update
        sudo apt-get install libsfml-dev

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ../src
        make

    - name: Install Stockfish
      run: |
        sudo apt-get update
        sudo apt-get install -y stockfish

    - name: Run Perft Test
      run: |
        echo "position fen 8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - " > sf_commands.txt
        echo "go perft 7" >> sf_commands.txt
        /usr/games/stockfish < sf_commands.txt > stockfish_output.txt
        /usr/bin/xvfb-run -a ./build/ChessEngine --perft 7 --fen "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - " --no-gui > engine_output.txt
        python ComparePerftResults.py engine_output.txt stockfish_output.txt
