name: Perft Pos2

on:
  push:
    branches:
      - main # Change this to your main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    name: perft2
    runs-on: ubuntu-latest # You can also use macos-latest for macOS

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pybind11
      run: pip install pybind11
    
    - name: Initialize and update submodule
      run: git submodule update --init --recursive

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.27'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.2.*'
        host: 'linux'

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ../
        make

    - name: Install Stockfish
      run: |
        sudo apt-get update
        sudo apt-get install -y stockfish

    - name: Run Perft Test
      run: |
        echo "position fen r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq -" > sf_commands.txt
        echo "go perft 6" >> sf_commands.txt
        /usr/games/stockfish < sf_commands.txt > stockfish_output.txt
        ./build/ChessEngine --perft 6 --fen "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq -" --no-gui > engine_output.txt
        python ComparePerftResults.py engine_output.txt stockfish_output.txt
