name: Perft Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Stockfish
        run: |
          sudo apt-get update
          sudo apt-get install -y stockfish

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://cmake.org/files/v3.27/cmake-3.27.0-Linux-x86_64.sh
          sudo sh cmake-3.27.0-Linux-x86_64.sh --prefix=/usr/local --skip-license
          sudo rm cmake-3.27.0-Linux-x86_64.sh

      - name: Build Chess Engine
        run: |
          mkdir build
          cd build
          cmake ..
          make || exit 1 # Fail the action if make fails

      - name: Run Perft Test
        run: |
          /usr/games/stockfish
          position startpos
          go perft 7 > stockfish_output.txt

          ./build/ChessEngine --perft 7 --no-gui > engine_output.txt
          python ComprePerftResults.py engine_output.txt stockfish_output.txt
        
